### ISSUE TITLE
logger crushes file service server 

### ISSUE THREAD

**Issue by OryanOmer** [meateam/file-service#164]
Problem with connection to ELASTIC server with the ERROR message:
Elasticsearch index error { _index: 'kdrive-2019.10.06',
  _type: 'log',
  _id: 'fC-RoW0Bei1Xu2WbEGZW',
  status: 400,
  error:
   { type: 'illegal_argument_exception',
     reason:
      'Rejecting mapping update to [kdrive-2019.10.06] as the final mapping would have more than 1 type: [_doc, log]' } }

**Comment by Shahar-Y** [comment]
Could not recreate error. Closing for now.
