### ISSUE TITLE
BUG: user gets error only at the end of upload when parallel uploading the same file

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/file-service#195]
On two occasions there is an error only after resumable upload of the the file finishes:
 - when the user uploads the same two files at the same time in the ui. (there can be two upload objects)
 - when the client  uploads the file via the gateway (directly) while another with same attributes already exists.

Due to rollback, it just wastes time for the user and doesn't harm the dbs.

**Comment by AllKinds** [comment]
Apparently a problem similar to #62 .
@Shahar-Y commented [this](https://github.com/meateam/file-service/issues/62#issuecomment-499209660), but not changes made to avoid the problem.
A test was written, but was passing either way.
