### ISSUE TITLE
DeleteFile gives "Unknown Error"

### ISSUE THREAD

**Issue by omrishtam** [meateam/file-service#31]
![image](https://user-images.githubusercontent.com/11276898/56901541-12d8fc80-6aa1-11e9-86bf-f07a2b59e820.png) ?
I gave it a valid file id and it returned this error.

**Comment by omrishtam** [comment]
Apparently it does delete the file but still returns an error

**Comment by omrishtam** [comment]
Fixed it

**Comment by Shahar-Y** [comment]
so.. fixed or not? and where?

**Comment by omrishtam** [comment]
I fixed it and committed and *thought* I pushed it to dev branch...but I didn't.. 😕 
The bug is in [`FileService.delete(id).then(() => callback({ ok: true }))`](https://github.com/meateam/file-service/blob/4c6e37a41a6fff8f25f39626645ca24206d7e559/src/file/file.rpc.ts#L120), it should be ` FileService.delete(id).then(() => callback(*null*, { ok: true }))` because the first parameter of the callback to the RPC response is the error if occurred, and the second is the value.
