### ISSUE TITLE
Edit error messages

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/file-service#32]
- [x] De-capitalize first letters of the error message
- [x] Add status code to error classes

**Comment by Shahar-Y** [comment]
@omrishtam check if it worked for you on the branch 'bugfix/errors', and comment here so I can create a pull request to dev.

**Comment by omrishtam** [comment]
Yes, it works now.
![image](https://user-images.githubusercontent.com/11276898/57196932-19b4b300-6f6a-11e9-84c0-508e4c44b077.png)

**Comment by omrishtam** [comment]
Done in #42

**Comment by Shahar-Y** [comment]
Need to fix status codes from http to rpc

**Comment by Shahar-Y** [comment]
@omrishtam @omerzamir 
I have updated the error codes. please go through the last commit and see if this is what you meant.

**Comment by Shahar-Y** [comment]
Done in #65
