### ISSUE TITLE
Cannot create a file that its name starts with '.'

### ISSUE THREAD

**Issue by omrishtam** [meateam/file-service#47]
For example trying to create a file with fullName of '.env' or '.omer.omri' would give an error `File validation failed: displayName: Path 'displayName' is required`

**Comment by omrishtam** [comment]
Also creating files with the same prefix until the first occurrence of '.' character would consider them as the same file.

**Comment by Shahar-Y** [comment]
Done in #58.
Reopen if the problem continues.

**Comment by omrishtam** [comment]
Add a test that the problem is solved and then close it if the test passes.
