### ISSUE TITLE
Files at the root level should have their parent be equal null

### ISSUE THREAD

**Issue by omrishtam** [meateam/file-service#53]
Files that are at the root level of the user's drive should have their parent be equal to null.

Currently there's a File model created specifically for representing the root folder with the boolean field `isRootFolder`, and the files' parent at the root folder is equal to the id of that "file".
So after making this change the `isRootFolder` field should be removed from the file's schema.

Tests should be changed accordingly.

**Comment by Shahar-Y** [comment]
Done in #64.
