### ISSUE TITLE
Feature - Limit user's storage

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/file-service#61]
Create bucket collection with its id and total size in order to limit storage per user. 
- [x] Create Bucket collection.
- [x] Add bucket side updates where needed.
- [x] Enforce Bucket size check with limiting while Creating a file in bucket Or creating Upload. 
- [x] Add function that checks if file can be uploaded(if there is enough space in the bucket).

**Comment by Shahar-Y** [comment]
PR #76 closes this issue

**Comment by Shahar-Y** [comment]
@omrishtam want to close it?

**Comment by omrishtam** [comment]
Closed in #76
