### ISSUE TITLE
missing check on update upload whether the file name is already found in the folder

### ISSUE THREAD

**Issue by omrishtam** [meateam/file-service#62]
Currently we create an upload model with its ID and file name, and later updating it with the bucket and key of the file that is being uploaded.

There’s a bug where the file being uploaded has the same name as another file under the same folder it’s being uploaded to.

The bug is that there’s no check on the created upload whether the name of the file being uploaded is already found in that folder, so a user can only get an error on that at the end of the upload (potentially 5TB upload) when we complete it and use CreateFile which does check that and returns the error.

**Comment by Shahar-Y** [comment]
what if two uploads are created at the same time with the same file (name, folder and owner)? 
do we check for that or let createFile deal with it? because if we do, we probably need to change the upload schema.

**Comment by omrishtam** [comment]
These fields make a unique index so there couldn’t be two of these, the database would give an error.

[also check this](http://lmgtfy.com/?q=database+transaction)

**Comment by Shahar-Y** [comment]
yes, but the createFile method is called at the end of the upload.
so the system will detect that only at the end of the upload anyways( again, if both files are uploaded simultaneously)

**Comment by omrishtam** [comment]
Understood, so the upload schema should also have unique index of these fields to validate with the database that they don’t repeat.

**Comment by omerzamir** [comment]
Just throwing it into the discussion, 
There is option to index on fields from different collections(index across collections) maybe it'll help you 🤷🏻‍♂️

**Comment by Shahar-Y** [comment]
Done in #69
