### ISSUE TITLE
Cannot read property 'split' of undefined 

### ISSUE THREAD

**Issue by omerzamir** [meateam/file-service#70]
rpc error: code = Unknown desc = Cannot read property 'split' of undefined 
when calling /api/files on api gateway, you dont have logs so i cant know where the problem is.

**Comment by Shahar-Y** [comment]
which method throws this error?

**Comment by omrishtam** [comment]
> which method throws this error?

🙄 We talked about it already...

**Comment by Shahar-Y** [comment]
yes, i confused between the two bug issues you two opened

**Comment by Shahar-Y** [comment]
Done in #75
