### ISSUE TITLE
undefined is already in use on file upload

### ISSUE THREAD

**Issue by omrishtam** [meateam/file-service#90]
![image](https://user-images.githubusercontent.com/11276898/60796249-bae00580-a175-11e9-9df0-284be3fed918.png)
This error appears sometimes randomly when uploading a file (bigger or smaller than 5MB) to the application and its returned from the file-service.

**Comment by Shahar-Y** [comment]
do you run it with the latest master?

**Comment by omrishtam** [comment]
This specific error didn't run from `master` but from `feature/logging`.
But I also remember that I encountered it while running it from `master` but I don't remember when, do you know if this is fixed in master? If so I'll close the issue for being irrelevant.

**Comment by Shahar-Y** [comment]
#107 should fix this problem

**Comment by Shahar-Y** [comment]
Done in #110
